import sys
from asammdf import MDF, Signal
import numpy as np
from PIL import Image

if __name__=='__main__':
        if len(sys.argv) < 4 :
           print("Usage: python mdf_Image_Frame_Generator.py <ImagePath> <NoOfCyclesInImage> <OutputMDF4FileName>")
           print("Sample usage: python mdf_Image_Frame_Generator.py sample.jpg 347 output.mf4")
        else:
            image_path = sys.argv[1]
            cycles = sys.argv[2]
            mdf4_output_file_name_with_path = sys.argv[3]

            sigs = []

            mdf = MDF()

            t = np.arange(int(cycles), dtype=np.float64)

            imgarray = np.array(Image.open(image_path))

            sig = Signal(
                         np.array(imgarray),
                         t,
                         name='Sample_Image_Frame',
                         comment='Image frame generated by HCL',
                        )
            sigs.append(sig)

            mdf.append(sigs, 'Image frame sample channels', common_timebase=True)

            mdf.save(mdf4_output_file_name_with_path, overwrite=True)
